# Daftar Pustaka {.unnumbered}

1.	UNEP. Beyond an Age of Waste Turning Rubbish into a Resource. https://wedocs.unep.org/20.500.11822/44939 (2024).
2.	UNEP. Beyond an Age of Waste Turning Rubbish into a Resource. (2024).
3.	Kaza, S. & Bhada-Tata, P. Decision Maker’s Guides for Solid Waste Management Technologies. (2018).
4.	UNEP. WASTE TO ENERGY CONSIDERATIONS FOR INFORMED DECISION-MAKING. (2019).
5.	MoE. History and Current State of Waste Management in Japan. (2014).
6.	LMOP. LFG Energy Project Development Handbook. (US EPA, 2024).
7.	Fischer, C. Municipal Waste Management in Germany. http://www.cri.dk/ (2013).
8.	Neuwahl, F., Cusano, G., Benavides, J. G., Holbrook, S. & Roudier, S. Best Available Techniques (BAT) Reference Document for Waste Incineration. (2019).
9.	Ittershagen, M. THE ROLE OF WASTE INCINERATION IN GERMANY. www.umweltbundesamt.de (2008).
10.	Koelsch, F. Stability Problems of Landfills-The Payatas Landslide.
11.	Kamuk, B. ISWA Guidelines: Waste to Energy in Low and Middle Income Countries. (2013).
12.	Lahl, U. & Zeschmar-Lahl, B. Prerequisites for Public Acceptance of Waste-to-Energy Plants: Evidence from Germany and Indonesia. Makara Journal of Technology 22, 17 (2018).
13.	UNEP. WASTE TO ENERGY CONSIDERATIONS FOR INFORMED DECISION-MAKING. (2019).
14.	Levaggi, L., Levaggi, R., Marchiori, C. & Trecroci, C. Waste-to-energy in the EU: The effects of plant ownership, waste mobility, and decentralization on environmental outcomes and welfare. Sustainability (Switzerland) 12, 1–12 (2020).
15.	Kalogirou, E. N. Waste-to-Energy Technologies and Global Applications. (CRC Press, Florida, 2018).
16.	Kleis, H. & Dalager, S. 100 YEARS OF WASTE INCINERATION IN DENMARK From Refuse Destruction Plants to High-Technology Energy Works. (2007).
17.	Jofra Sora, M. Incineration Overcapacity and Waste Shipping in Europe: The End of the Proximity Principle? (2013).
18.	JICA. Japan’s Experiences on Waste Management: Overview. (2024).
19.	Dolgen, D., Sarptas, H., Alpaslan, N. & Kucukgul, O. Energy potential of municipal solid wastes. Energy Sources 27, 1483–1492 (2005).
20.	Wahyono, S. Mengelola Sampah Ala Singapura: Model Pengelolaan Sampah Kota Metropolitan. (BPPT Press, Jakarta, 2003).
21.	Fischer, C. Municipal Waste Management in Germany. http://www.cri.dk/ (2013).
22.	Syifaa, N., Shakil, M., Zahida, A., Azhar, M. & Othman, N. Solid Waste Management in Malaysia: An Overview. Information Management and Business Review vol. 15 (2023).
23.	Manaf, L. A., Samah, M. A. A. & Zukki, N. I. M. Municipal solid waste management in Malaysia: Practices and challenges. Waste Management 29, 2902–2906 (2009).
24.	Jade, C. Batu Arang residents rally against proposed WTE plant, citing health, environmental concerns . https://www.thestar.com.my/metro/metro-news/2025/11/17/batu-arang-residents-rally-against-proposed-wte-plant-citing-health-environmental-concerns#goog_rewarded (2025).
25.	Chand Malav, L. et al. A review on municipal solid waste as a renewable source for waste-to-energy project in India: Current practices, challenges, and future opportunities. J Clean Prod 277, (2020).
26.	Kaza, S., Yao, L., Bhada-Tata, P. & Van Woerden, F. What a Waste 2.0. (2018).
27.	Wahyono, S., Sahwan, F. L. & Suryanto, F. Characterization of municipal solid waste for waste to energy feedstock in Jakarta. in IOP Conference Series: Earth and Environmental Science vol. 1034 (Institute of Physics, 2022).
28.	Wahyono, S. et al. Identification and analysis of municipal solid waste pre-treatment to improve waste quality for waste-to-energy facility. in IOP Conference Series: Earth and Environmental Science vol. 1201 (Institute of Physics, 2023).
29.	UNEP. General Technical Guidelines on the Environmentally Sound of Wastes Consisting of, Containing or contaminated with Persistent Organic Pollutants. (2024).
30.	Syahputra, R., Kristanto, G. A. & Dahlan, A. V. The Potential Integration of Informal to Formal Workers in Muara Fajar Landfill (TPA) Pekanbaru with the Circular Economy Concept. Indonesian Journal of Social Technology 6, 872 (2025).
31.	GIZ. INCLUSION OF INFORMAL COLLECTORS INTO THE EVOLVING WASTE MANAGEMENT SYSTEM IN SERBIA : A Roadmap for Integration. www.giz.de (2018).
32.	Damanhuri, E. Informal Collectors of Recyclable Waste and Used Goods in Indonesia. (2010).
33.	Pemkot Yogyakarta. Peraturan Walikota Yogyakarta No 32 Tahun 2022 Tentang Masterplan Pengelolaan Persampahan Kota Yogyakarta 2022 - 2031. (2022).
34.	Quina, M. J., Bordado, J. C. M. & Quinta-Ferreira, R. M. Air Pollution Control in Municipal Solid Waste Incinerators. in The Impact of Air Pollution on Health, Economy, Environment and Agricultural Sources (ed. Khallaf, M. K.) (InTech, 2011).
35.	Deltaway. Waste-to-Energy: How It Works. https://deltawayenergy.com/2018/08/waste-to-energy-how-it-works/.
36.	Wood, S., Fanning, M., Venn, M. & Whiting, K. REVIEW OF STATE-OF-THE-ART WASTE-TO-ENERGY TECHNOLOGIES. www.wspgroup.co.uk (2013).
37.	Moshkal, M., Akhapov, Y. & Ogihara, A. Sustainable Waste Management in Japan: Challenges, Achievements, and Future Prospects: A Review. Sustainability (Switzerland) vol. 16 Preprint at https://doi.org/10.3390/su16177347 (2024).
38.	Albizzati, P. Federica. et al. Development of an EU Harmonised Model for Separate Municipal Waste Collection and Related Policy Support. (2023).
39.	European Commission. Being Wise with Waste : The EU’s Approach to Waste Management. (2010).
40.	Yumitro, G., Oktaviani, S. & Deniar, S. M. How South Korea’s waste management system becomes a model for the world: What Indonesia can learn from South Korea’s experience. Communications in Humanities and Social Sciences 4, 22–28 (2024).
41.	GIZ. INCLUSION OF INFORMAL COLLECTORS INTO THE EVOLVING WASTE MANAGEMENT SYSTEM IN SERBIA A Roadmap for Integration. www.giz.de (2018).
42.	ISWA. Waste-to-Energy State-of-the-Art-Report. www.ramboll.com (2012).