# Kata Pengantar {.unnumbered}

Puji syukur kami panjatkan ke hadirat Allah SWT atas limpahan rahmat-Nya sehingga buku ini dapat disusun dengan baik. Buku ini ditulis untuk menyongsong era baru pengelolaan sampah di Indonesia dengan diterbitkannya Perpres 109/2025 yang mengedepankan pengolahan sampah menjadi energi dengan teknologi yang ramah lingkungan. Pengolahan Sampah menjadi Energi Listrik (PSEL) menjadi harapan baru khususnya bagi beberapa kota besar di Indonesia yang mengalami krisis persampahan.

Kesempatan emas ini seharusnya bisa kita manfaatkan bukan hanya mengatasi krisis sampah yang sudah kian parah namun sebaiknya sekaligus membenahi tata kelola persampahan dari hulu sampai ke hilir. Sehebat apapun teknologi Waste to Energy (WtE) yang akan dibangun tidak akan berkelanjutan jika tanpa didukung oleh pengelolaan yang memadai sejak dari sumber sampah.

Dalam proses penyusunan naskah ini kami sangat berterima kasih kepada teman-teman diskusi yang tergabung dalam ISWF (Indonesian Solid Waste Forum) khususnya kepada bapak Agunan P. Samosir, yang sangat membantu dalam mendalami mengenai kebijakan fiskal dan pembiayaan bidang persampahan, serta Dr. Hijrah Purnama Putra, Dr. Fajri Mulya Iresha dan Dr.(cand.) Yebi Yuriandala yang memberikan insight dalam pengelolaan sampah berbasis masyarakat. Ucapan terimakasih kepada teman kami, Dr. Bayu Indrawan, atas saran-saran perbaikan dan tambahan materi khususnya mengenai WtE yang sangat berharga dalam peningkatan kualitas isi buku ini dan juga kepada Prof. Prabang Setyono yang memberikan saran mengenai pengukuran keberlanjutan. Kami juga banyak mengucapkan terimakasih kepada teman-teman kami dalam penelitian dan publikasi bidang persampahan Prof. Zahrul Mufrodi, Dr. Syamsiro, Dr. Agus Prasetya, Dr. Pandji Prawisudha dan Dr. Kun Sri Budiasih, Dr. R.B. Seno Wulung, dan Dr.(cand.) M. Noviansyah Aridito serta semua pihak yang berkontribusi dalam penyusunan buku ini yang tidak dapat kami sebutkan satu per satu. 

Semoga buku ini dapat dipakai sebagai rujukan oleh berbagai kalangan mulai dari akademisi, para penggiat persampahan, sampai dengan para pimpinan daerah khususnya yang akan menangani persampahan dengan teknologi WtE. Terkhusus untuk memberikan arahan bagi pemangku kebijakan di daerah, pada akhir tiap bab diberikan poin-poin rekomendasi dalam boks khusus yang perlu diambil guna bertransformasi menuju pengelolaan sampah berbasis teknologi. Tentunya saran dan kritik terus diharapkan untuk perbaikan isi buku ke depan sehingga edisi berikutnya akan lebih sempurna.



Hormat kami,

Chandra W. Purnomo

Sri Wahyono